export const REQUEST_INCIDENT = 'app/OverviewPage/REQUEST_INCIDENT';
export const REQUEST_INCIDENT_SUCCESS = 'app/OverviewPage/REQUEST_INCIDENT_SUCCESS';
export const REQUEST_INCIDENT_ERROR = 'app/OverviewPage/REQUEST_INCIDENT_ERROR';
