export const DJANGO = {
  buttonSave: '[name="_save"]',
  checkboxCanDirect: '#id_can_direct',
  checkboxTemplate: '.action-select',
  inputEmailBody: '#id_body',
  inputEmailTitle: '#id_title',
  inputPassword: '#id_password',
  inputUsername: '#id_username',
  linkDepartment: 'a[href="/signals/admin/signals/department/"]',
  linkEmailTemplate: 'a[href="/signals/admin/email_integrations/emailtemplate/"]',
  linkEmailTemplateAdd: 'a[href="/signals/admin/email_integrations/emailtemplate/add/"]',
  linkLogout: 'a[href="/signals/admin/logout/"]',
  templateList: '#changelist',
  selectEmailKey: '#id_key',
};
