// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2020 - 2022 Gemeente Amsterdam
export const SAME_REPORTER = {
  buttonPaginationNext: '[data-testid=nextbutton]',
  buttonPaginationPrevious: '[data-testid=prevbutton]',
  dateTime: '[data-testid=date-time]',
  feedbackStatus: '[data-testid=feedback-status]',
  iconHoofdmelding: '[data-testid=parent-icon]',
  incidentDescription: '[data-testid=incident-description]',
  incidentHeading: '[data-testid=incident-heading]',
  incidentInfo: '[data-testid=incident-info]',
  incidentStatus: '[data-testid=incident-status]',
  labelGemeldOp: '[data-testid=label-date-definition]',
  labelHistory: '[data-testid=label-history]',
  labelStatus: '[data-testid=label-status]',
  labelSubcategory: '[data-testid=label-subcategory]',
  linkBackToSignal: '[data-testid=backlink]',
  reportcontainer: '[data-testid=reporter-container]',
  textNoContactHistory: '[data-testid=no-contact-history]',
  valueGemeldOp: '[data-testid=value-date-definition]',
  valueStatus: '[data-testid=value-status]',
  valueSubcategory: '[data-testid=value-subcategory]',
};

export const SAME_AREA = {
  areaLabel: '[data-testid="area-label"]',
  backToFilterLink: '[data-testid="backlink"]',
  buttonCloseMap: '[data-testid="map-close-button"]',
  buttonZoomIn: '[title="Inzoomen"]',
  buttonZoomOut: '[title="Uitzoomen"]',
  clustericon: '.marker-cluster',
  dateLabel: '[data-testid="date-label"]',
  icon: '.leaflet-marker-icon',
  kindLabel: '[data-testid="kind-label"]',
  locationLabel: '[data-testid="location-label"]',
  map: '[data-testid="map-base"]',
  period: '[data-testid="period"]',
  periodLabel: '[data-testid="period-label"]',
  statusLabel: '[data-testid="status-label"]',
  signalDate: '[data-testid="date"]',
  signalDepartments: '[data-testid="departments"]',
  signalLabel: 'a:contains("melding")',
  signalLocation: '[data-testid="location"]',
  signalStatus: '[data-testid="status"]',
  signalText: '[data-testid="text"]',
  signalSubcategory: '[data-testid="subcategory"]',
  subcategoryLabel: '[data-testid="subcategory-label"]',
  zoomButtons: '[data-testid="map-zoom"]',
};
