export const REQUEST_CATEGORY_UPDATE = 'app/IncidentStatusContainer/REQUEST_CATEGORY_UPDATE';
export const REQUEST_CATEGORY_UPDATE_SUCCESS = 'app/IncidentStatusContainer/REQUEST_CATEGORY_UPDATE_SUCCESS';
export const REQUEST_CATEGORY_UPDATE_ERROR = 'app/IncidentStatusContainer/REQUEST_CATEGORY_UPDATE_ERROR';
