export const REQUEST_INCIDENTS = 'src/OverviewPage/REQUEST_INCIDENTS';
export const REQUEST_INCIDENTS_SUCCESS = 'src/OverviewPage/REQUEST_INCIDENTS_SUCCESS';
export const REQUEST_INCIDENTS_ERROR = 'src/OverviewPage/REQUEST_INCIDENTS_ERROR';

export const INCIDENT_SELECTED = 'src/OverviewPage/INCIDENT_SELECTED';
export const FILTER_INCIDENTS_CHANGED = 'src/OverviewPage/FILTER_INCIDENTS_CHANGED';
export const PAGE_INCIDENTS_CHANGED = 'src/OverviewPage/PAGE_INCIDENTS_CHANGED';
