export enum QuestionFieldType {
  AssetSelect = 'AssetSelectRenderer',
  CaterpillarSelect = 'CaterpillarSelectRenderer',
  CheckboxInput = 'CheckboxInput',
  ClockSelect = 'ClockSelectRenderer',
  DateTimeInput = 'DateTimeInput',
  DescriptionInput = 'DescriptionInputRenderer',
  EmphasisCheckboxInput = 'EmphasisCheckboxInput',
  FileInput = 'FileInputRenderer',
  HandlingMessage = 'HandlingMessage',
  Header = 'Header',
  HiddenInput = 'HiddenInput',
  LocationSelect = 'AssetSelectRenderer',
  MapInput = 'MapInput',
  MultiTextInput = 'MultiTextInput',
  PlainText = 'PlainText',
  RadioInput = 'RadioInputGroup',
  SelectInput = 'SelectInput',
  StreetlightSelect = 'StreetlightSelectRenderer',
  TextInput = 'TextInput',
  TextareaInput = 'TextareaInput',
}
