export const REQUEST_INCIDENT = 'sia/IncidentModel/REQUEST_INCIDENT';
export const REQUEST_INCIDENT_SUCCESS = 'sia/IncidentModel/REQUEST_INCIDENT_SUCCESS';
export const REQUEST_INCIDENT_ERROR = 'sia/IncidentModel/REQUEST_INCIDENT_ERROR';
