export const REQUEST_INCIDENT = 'sia/incidentModel/REQUEST_INCIDENT';
export const REQUEST_INCIDENT_SUCCESS = 'sia/incidentModel/REQUEST_INCIDENT_SUCCESS';
export const REQUEST_INCIDENT_ERROR = 'sia/incidentModel/REQUEST_INCIDENT_ERROR';

export const DISMISS_ERROR = 'sia/incidentModel/DISMISS_ERROR';

export const REQUEST_ATTACHMENTS = 'sia/incidentModel/REQUEST_ATTACHMENTS';
export const REQUEST_ATTACHMENTS_SUCCESS = 'sia/incidentModel/REQUEST_ATTACHMENTS_SUCCESS';
export const REQUEST_ATTACHMENTS_ERROR = 'sia/incidentModel/REQUEST_ATTACHMENTS_ERROR';

export const REQUEST_DEFAULT_TEXTS = 'src/incidentModel/REQUEST_DEFAULT_TEXTS';
export const REQUEST_DEFAULT_TEXTS_SUCCESS = 'src/incidentModel/REQUEST_DEFAULT_TEXTS_SUCCESS';
export const REQUEST_DEFAULT_TEXTS_ERROR = 'src/incidentModel/REQUEST_DEFAULT_TEXTS_ERROR';
