export const REQUEST_INCIDENT = 'src/OverviewPage/REQUEST_INCIDENT';
export const REQUEST_INCIDENT_SUCCESS = 'src/OverviewPage/REQUEST_INCIDENT_SUCCESS';
export const REQUEST_INCIDENT_ERROR = 'src/OverviewPage/REQUEST_INCIDENT_ERROR';
