export const REQUEST_CATEGORY_UPDATE = 'sia/IncidentCategoryContainer/REQUEST_CATEGORY_UPDATE';
export const REQUEST_CATEGORY_UPDATE_SUCCESS = 'sia/IncidentCategoryContainer/REQUEST_CATEGORY_UPDATE_SUCCESS';
export const REQUEST_CATEGORY_UPDATE_ERROR = 'sia/IncidentCategoryContainer/REQUEST_CATEGORY_UPDATE_ERROR';
