export const REQUEST_CATEGORY_UPDATE = 'src/IncidentStatusContainer/REQUEST_CATEGORY_UPDATE';
export const REQUEST_CATEGORY_UPDATE_SUCCESS = 'src/IncidentStatusContainer/REQUEST_CATEGORY_UPDATE_SUCCESS';
export const REQUEST_CATEGORY_UPDATE_ERROR = 'src/IncidentStatusContainer/REQUEST_CATEGORY_UPDATE_ERROR';
