/* eslint-disable */

const mainToSubMap = {
  '': [
    'Veeg- / zwerfvuil',
    'Grofvuil',
    'Huisafval',
    'Bedrijfsafval',
    'Puin / sloopafval',
    'Container is vol',
    'Prullenbak is vol',
    'Container is kapot',
    'Prullenbak is kapot',
    'Asbest / accu',
    'Overig afval',
    'Container voor plastic afval is vol',
    'Container voor plastic afval is kapot',
    'Onderhoud stoep, straat en fietspad',
    'Verkeersbord, verkeersafzetting',
    'Gladheid',
    'Omleiding / belijning verkeer',
    'Brug',
    'Straatmeubilair',
    'Fietsrek / nietje',
    'Put / riolering verstopt',
    'Speelplaats',
    'Sportvoorziening',
    'Straatverlichting / openbare klok',
    'Klok',
    'Verkeerslicht',
    'Overig Wegen, verkeer, straatmeubilair',
    'Verkeersoverlast / Verkeerssituaties',
    'Lozing / dumping / bodemverontreiniging',
    'Parkeeroverlast',
    'Fietswrak',
    'Stank- / geluidsoverlast',
    'Bouw- / sloopoverlast',
    'Auto- / scooter- / bromfiets(wrak)',
    'Graffiti / wildplak',
    'Honden(poep)',
    'Hinderlijk geplaatst object',
    'Deelfiets',
    'Overig openbare ruimte',
    'Boom',
    'Maaien / snoeien',
    'Onkruid',
    'Drijfvuil',
    'Oever / kade / steiger',
    'Overig groen en water',
    'Ratten',
    'Ganzen',
    'Duiven',
    'Meeuwen',
    'Wespen',
    'Dode dieren',
    'Overig dieren',
    'Vuurwerkoverlast',
    'Overlast door afsteken vuurwerk',
    'Overige overlast door personen',
    'Personen op het water',
    'Overlast van taxi\'s, bussen en fietstaxi\'s',
    'Jongerenoverlast',
    'Daklozen / bedelen',
    'Wildplassen / poepen / overgeven',
    'Drank- en drugsoverlast',
    'Geluidsoverlast muziek',
    'Geluidsoverlast installaties',
    'Overlast terrassen',
    'Stankoverlast',
    'Overlast door bezoekers (niet op terras)',
    'Overig horeca/bedrijven',
    'Overlast op het water - snel varen',
    'Overlast op het water - Vaargedrag',
    'Overlast op het water - geluid',
    'Overlast op het water - Gezonken boot',
    'Scheepvaart nautisch toezicht',
    'Overlast vanaf het water',
    'Overig boten',
    'Overig'
  ],
  'Afval': [
    'Veeg- / zwerfvuil',
    'Grofvuil',
    'Huisafval',
    'Bedrijfsafval',
    'Puin / sloopafval',
    'Container is vol',
    'Prullenbak is vol',
    'Container is kapot',
    'Prullenbak is kapot',
    'Asbest / accu',
    'Overig afval',
    'Container voor plastic afval is vol',
    'Container voor plastic afval is kapot'
  ],
  'Wegen, verkeer, straatmeubilair': [
    'Onderhoud stoep, straat en fietspad',
    'Verkeersbord, verkeersafzetting',
    'Gladheid',
    'Omleiding / belijning verkeer',
    'Brug',
    'Straatmeubilair',
    'Fietsrek / nietje',
    'Put / riolering verstopt',
    'Speelplaats',
    'Sportvoorziening',
    'Straatverlichting / openbare klok',
    'Klok',
    'Verkeerslicht',
    'Overig Wegen, verkeer, straatmeubilair',
    'Verkeersoverlast / Verkeerssituaties'
  ],
  'Overlast in de openbare ruimte': [
    'Lozing / dumping / bodemverontreiniging',
    'Parkeeroverlast',
    'Fietswrak',
    'Stank- / geluidsoverlast',
    'Bouw- / sloopoverlast',
    'Auto- / scooter- / bromfiets(wrak)',
    'Graffiti / wildplak',
    'Honden(poep)',
    'Hinderlijk geplaatst object',
    'Deelfiets',
    'Overig openbare ruimte'
  ],
  'Openbaar groen en water': [
    'Boom',
    'Maaien / snoeien',
    'Onkruid',
    'Drijfvuil',
    'Oever / kade / steiger',
    'Overig groen en water'
  ],
  'Overlast van dieren': [
    'Ratten',
    'Ganzen',
    'Duiven',
    'Meeuwen',
    'Wespen',
    'Dode dieren',
    'Overig dieren'
  ],
  'Overlast van en door personen of groepen': [
    'Vuurwerkoverlast',
    'Overlast door afsteken vuurwerk',
    'Overige overlast door personen',
    'Personen op het water',
    'Overlast van taxi\'s, bussen en fietstaxi\'s',
    'Jongerenoverlast',
    'Daklozen / bedelen',
    'Wildplassen / poepen / overgeven',
    'Drank- en drugsoverlast'
  ],
  'Overlast Bedrijven en Horeca': [
    'Geluidsoverlast muziek',
    'Geluidsoverlast installaties',
    'Overlast terrassen',
    'Stankoverlast',
    'Overlast door bezoekers (niet op terras)',
    'Overig horeca/bedrijven'
  ],
  'Overlast op het water': [
    'Overlast op het water - snel varen',
    'Overlast op het water - Vaargedrag',
    'Overlast op het water - geluid',
    'Overlast op het water - Gezonken boot',
    'Scheepvaart nautisch toezicht',
    'Overlast vanaf het water',
    'Overig boten'
  ],
  'Overig': ['Overig']
}

export default mainToSubMap;
