const subcategoryList = [
  { key: 'Asbest / accu', value: 'Asbest / accu' },
  { key: 'Auto- /scooter- / bromfiets(wrak)', value: 'Auto- /scooter- / bromfiets(wrak)' },
  { key: 'Bedrijfsafval', value: 'Bedrijfsafval' },
  { key: 'Boom', value: 'Boom' },
  { key: 'Bouw- / sloopoverlast', value: 'Bouw- / sloopoverlast' },
  { key: 'Brug', value: 'Brug' },
  { key: 'Container is kapot', value: 'Container is kapot' },
  { key: 'Container is vol', value: 'Container is vol' },
  { key: 'Container voor plastic afval is kapot', value: 'Container voor plastic afval is kapot' },
  { key: 'Container voor plastic afval is vol', value: 'Container voor plastic afval is vol' },
  { key: 'Daklozen / bedelen', value: 'Daklozen / bedelen' },
  { key: 'Deelfiets', value: 'Deelfiets' },
  { key: 'Dode dieren', value: 'Dode dieren' },
  { key: 'Drank- en drugsoverlast', value: 'Drank- en drugsoverlast' },
  { key: 'Drijfvuil', value: 'Drijfvuil' },
  { key: 'Duiven', value: 'Duiven' },
  { key: 'Fietsrek / nietje', value: 'Fietsrek / nietje' },
  { key: 'Fietswrak', value: 'Fietswrak' },
  { key: 'Geluidsoverlast installaties', value: 'Geluidsoverlast installaties' },
  { key: 'Geluidsoverlast muziek', value: 'Geluidsoverlast muziek' },
  { key: 'Gladheid', value: 'Gladheid' },
  { key: 'Graffiti / wildplak', value: 'Graffiti / wildplak' },
  { key: 'Grofvuil', value: 'Grofvuil' },
  { key: 'Hinderlijk geplaatst object', value: 'Hinderlijk geplaatst object' },
  { key: 'Honden(poep)', value: 'Honden(poep)' },
  { key: 'Huisafval', value: 'Huisafval' },
  { key: 'Jongerenoverlast', value: 'Jongerenoverlast' },
  { key: 'Lozing / dumping / bodemverontreiniging', value: 'Lozing / dumping / bodemverontreiniging' },
  { key: 'Maaien / Snoeien', value: 'Maaien / Snoeien' },
  { key: 'Meeuwen', value: 'Meeuwen' },
  { key: 'Oever / kade / steiger', value: 'Oever / kade / steiger' },
  { key: 'Omleiding / belijning verkeer', value: 'Omleiding / belijning verkeer' },
  { key: 'Onderhoud stoep, straat en fietspad', value: 'Onderhoud stoep, straat en fietspad' },
  { key: 'Onkruid', value: 'Onkruid' },
  { key: 'Overige overlast door personen', value: 'Overige overlast door personen' },
  { key: 'Overlast door afsteken vuurwerk', value: 'Overlast door afsteken vuurwerk' },
  { key: 'Overlast door bezoekers (niet op terras)', value: 'Overlast door bezoekers (niet op terras)' },
  { key: 'Overlast op het water - geluid', value: 'Overlast op het water - geluid' },
  { key: 'Overlast op het water - Gezonken boot', value: 'Overlast op het water - Gezonken boot' },
  { key: 'Overlast op het water - snel varen', value: 'Overlast op het water - snel varen' },
  { key: 'Overlast terrassen', value: 'Overlast terrassen' },
  { key: 'Overlast van taxi\'s, bussen en fietstaxi\'s', value: 'Overlast van taxi\'s, bussen en fietstaxi\'s' },
  { key: 'Overlast vanaf het water', value: 'Overlast vanaf het water' },
  { key: 'Parkeeroverlast', value: 'Parkeeroverlast' },
  { key: 'Prullenbak is kapot', value: 'Prullenbak is kapot' },
  { key: 'Prullenbak is vol', value: 'Prullenbak is vol' },
  { key: 'Puin / sloopafval', value: 'Puin / sloopafval' },
  { key: 'Put / riolering verstopt', value: 'Put / riolering verstopt' },
  { key: 'Ratten', value: 'Ratten' },
  { key: 'Scheepvaart nautisch toezicht', value: 'Scheepvaart nautisch toezicht' },
  { key: 'Speelplaats', value: 'Speelplaats' },
  { key: 'Sportvoorziening', value: 'Sportvoorziening' },
  { key: 'Stank- / geluidsoverlast', value: 'Stank- / geluidsoverlast' },
  { key: 'Stankoverlast', value: 'Stankoverlast' },
  { key: 'Straatmeubilair', value: 'Straatmeubilair' },
  { key: 'Straatverlichting / openbare klok', value: 'Straatverlichting / openbare klok' },
  { key: 'Veeg- / zwerfvuil', value: 'Veeg- / zwerfvuil' },
  { key: 'Verkeersbord, verkeersafzetting', value: 'Verkeersbord, verkeersafzetting' },
  { key: 'Verkeerslicht', value: 'Verkeerslicht' },
  { key: 'Verkeersoverlast / Verkeerssituaties', value: 'Verkeersoverlast / Verkeerssituaties' },
  { key: 'Vuurwerkoverlast', value: 'Vuurwerkoverlast' },
  { key: 'Wespen', value: 'Wespen' },
  { key: 'Wildplassen / poepen / overgeven', value: 'Wildplassen / poepen / overgeven' },
];

export default subcategoryList;

