const subcategoryList = [
  { key: '', value: 'Alles' },
  { key: 'Veeg- / zwerfvuil', value: 'Veeg- / zwerfvuil' },
  { key: 'Grofvuil', value: 'Grofvuil' },
  { key: 'Huisafval', value: 'Huisafval' },
  { key: 'Bedrijfsafval', value: 'Bedrijfsafval' },
  { key: 'Puin / sloopafval', value: 'Puin / sloopafval' },
  { key: 'Container is vol', value: 'Container is vol' },
  { key: 'Prullenbak is vol', value: 'Prullenbak is vol' },
  { key: 'Container is kapot', value: 'Container is kapot' },
  { key: 'Prullenbak is kapot', value: 'Prullenbak is kapot' },
  { key: 'Asbest / accu', value: 'Asbest / accu' },
  { key: 'Container plastic afval is vol', value: 'Container plastic afval is vol' },
  { key: 'Container plastic afval is kapot', value: 'Container plastic afval is kapot' },
  { key: 'Onderhoud stoep, straat, fietspad', value: 'Onderhoud stoep, straat, fietspad' },
  { key: 'Verkeersbord, verkeersafzetting', value: 'Verkeersbord, verkeersafzetting' },
  { key: 'Gladheid', value: 'Gladheid' },
  { key: 'Omleiding / belijning verkeer', value: 'Omleiding / belijning verkeer' },
  { key: 'Brug', value: 'Brug' },
  { key: 'Straatmeubilair', value: 'Straatmeubilair' },
  { key: 'Fietsenrek / nietje', value: 'Fietsenrek / nietje' },
  { key: 'Put / riolering verstopt', value: 'Put / riolering verstopt' },
  { key: 'Speelplaats', value: 'Speelplaats' },
  { key: 'Sportvoorziening', value: 'Sportvoorziening' },
  { key: 'Verkeersoverlast / Verkeerssituaties', value: 'Verkeersoverlast / Verkeerssituaties' },
  { key: 'Lozing / dumping / bodemverontreiniging', value: 'Lozing / dumping / bodemverontreiniging' },
  { key: 'Parkeeroverlast', value: 'Parkeeroverlast' },
  { key: 'Fietswrak', value: 'Fietswrak' },
  { key: 'Stank- / geluidsoverlast', value: 'Stank- / geluidsoverlast' },
  { key: 'Bouw- / sloopoverlast', value: 'Bouw- / sloopoverlast' },
  { key: 'Auto- /scooter- / bromfiets(wrak)', value: 'Auto- /scooter- / bromfiets(wrak)' },
  { key: 'Graffiti / wildplak', value: 'Graffiti / wildplak' },
  { key: 'Honden(poep)', value: 'Honden(poep)' },
  { key: 'Hinderlijk geplaatst object', value: 'Hinderlijk geplaatst object' },
  { key: 'Deelfiets', value: 'Deelfiets' },
  { key: 'Boom', value: 'Boom' },
  { key: 'Maaien / Snoeien', value: 'Maaien / Snoeien' },
  { key: 'Onkruid', value: 'Onkruid' },
  { key: 'Drijfvuil', value: 'Drijfvuil' },
  { key: 'Oever / kade / steiger', value: 'Oever / kade / steiger' },
  { key: 'Ratten', value: 'Ratten' },
  { key: 'Ganzen', value: 'Ganzen' },
  { key: 'Duiven', value: 'Duiven' },
  { key: 'Meeuwen', value: 'Meeuwen' },
  { key: 'Wespen', value: 'Wespen' },
  { key: 'Dode dieren', value: 'Dode dieren' },
  { key: 'Overlast door afsteken vuurwerk', value: 'Overlast door afsteken vuurwerk' },
  { key: 'Overlast vanaf het water', value: 'Overlast vanaf het water' },
  { key: 'Overlast van taxi’s, bussen en fietstaxi’s', value: 'Overlast van taxi’s, bussen en fietstaxi’s' },
  { key: 'Jongerenoverlast', value: 'Jongerenoverlast' },
  { key: 'Daklozen / bedelen', value: 'Daklozen / bedelen' },
  { key: 'Wildplassen / poepen / overgeven', value: 'Wildplassen / poepen / overgeven' },
  { key: 'Drank- en drugsoverlast', value: 'Drank- en drugsoverlast' },
  { key: 'Geluidsoverlast muziek', value: 'Geluidsoverlast muziek' },
  { key: 'Geluidsoverlast installaties', value: 'Geluidsoverlast installaties' },
  { key: 'Overlast terrassen', value: 'Overlast terrassen' },
  { key: 'Stankoverlast', value: 'Stankoverlast' },
  { key: 'Overlast door bezoekers (niet op terras)', value: 'Overlast door bezoekers (niet op terras)' },
  { key: 'Overlast op het water - snel varen', value: 'Overlast op het water - snel varen' },
  { key: 'Overlast op het water - geluid', value: 'Overlast op het water - geluid' },
  { key: 'Overlast op het water - Gezonken boot', value: 'Overlast op het water - Gezonken boot' },
  { key: 'Straatverlichting / openbare klok', value: 'Straatverlichting / openbare klok' },
  { key: 'Stoplicht', value: 'Stoplicht' },
];

export default subcategoryList;

