/* eslint-disable */

const subToMainMap = {
  'Veeg- / zwerfvuil': 'Afval',
  'Grofvuil': 'Afval',
  'Huisafval': 'Afval',
  'Bedrijfsafval': 'Afval',
  'Puin / sloopafval': 'Afval',
  'Container is vol': 'Afval',
  'Prullenbak is vol': 'Afval',
  'Container is kapot': 'Afval',
  'Prullenbak is kapot': 'Afval',
  'Asbest / accu': 'Afval',
  'Overig afval': 'Afval',
  'Container voor plastic afval is vol': 'Afval',
  'Container voor plastic afval is kapot': 'Afval',
  'Onderhoud stoep, straat en fietspad': 'Wegen, verkeer, straatmeubilair',
  'Verkeersbord, verkeersafzetting': 'Wegen, verkeer, straatmeubilair',
  'Gladheid': 'Wegen, verkeer, straatmeubilair',
  'Omleiding / belijning verkeer': 'Wegen, verkeer, straatmeubilair',
  'Brug': 'Wegen, verkeer, straatmeubilair',
  'Straatmeubilair': 'Wegen, verkeer, straatmeubilair',
  'Fietsrek / nietje': 'Wegen, verkeer, straatmeubilair',
  'Put / riolering verstopt': 'Wegen, verkeer, straatmeubilair',
  'Speelplaats': 'Wegen, verkeer, straatmeubilair',
  'Sportvoorziening': 'Wegen, verkeer, straatmeubilair',
  'Straatverlichting / openbare klok': 'Wegen, verkeer, straatmeubilair',
  'Klok': 'Wegen, verkeer, straatmeubilair',
  'Verkeerslicht': 'Wegen, verkeer, straatmeubilair',
  'Overig Wegen, verkeer, straatmeubilair': 'Wegen, verkeer, straatmeubilair',
  'Verkeersoverlast / Verkeerssituaties': 'Wegen, verkeer, straatmeubilair',
  'Lozing / dumping / bodemverontreiniging': 'Overlast in de openbare ruimte',
  'Parkeeroverlast': 'Overlast in de openbare ruimte',
  'Fietswrak': 'Overlast in de openbare ruimte',
  'Stank- / geluidsoverlast': 'Overlast in de openbare ruimte',
  'Bouw- / sloopoverlast': 'Overlast in de openbare ruimte',
  'Auto- / scooter- / bromfiets(wrak)': 'Overlast in de openbare ruimte',
  'Graffiti / wildplak': 'Overlast in de openbare ruimte',
  'Honden(poep)': 'Overlast in de openbare ruimte',
  'Hinderlijk geplaatst object': 'Overlast in de openbare ruimte',
  'Deelfiets': 'Overlast in de openbare ruimte',
  'Overig openbare ruimte': 'Overlast in de openbare ruimte',
  'Boom': 'Openbaar groen en water',
  'Maaien / snoeien': 'Openbaar groen en water',
  'Onkruid': 'Openbaar groen en water',
  'Drijfvuil': 'Openbaar groen en water',
  'Oever / kade / steiger': 'Openbaar groen en water',
  'Overig groen en water': 'Openbaar groen en water',
  'Ratten': 'Overlast van dieren',
  'Ganzen': 'Overlast van dieren',
  'Duiven': 'Overlast van dieren',
  'Meeuwen': 'Overlast van dieren',
  'Wespen': 'Overlast van dieren',
  'Dode dieren': 'Overlast van dieren',
  'Overig dieren': 'Overlast van dieren',
  'Vuurwerkoverlast': 'Overlast van en door personen of groepen',
  'Overlast door afsteken vuurwerk': 'Overlast van en door personen of groepen',
  'Overige overlast door personen': 'Overlast van en door personen of groepen',
  'Personen op het water': 'Overlast van en door personen of groepen',
  'Overlast van taxi\'s, bussen en fietstaxi\'s': 'Overlast van en door personen of groepen',
  'Jongerenoverlast': 'Overlast van en door personen of groepen',
  'Daklozen / bedelen': 'Overlast van en door personen of groepen',
  'Wildplassen / poepen / overgeven': 'Overlast van en door personen of groepen',
  'Drank- en drugsoverlast': 'Overlast van en door personen of groepen',
  'Geluidsoverlast muziek': 'Overlast Bedrijven en Horeca',
  'Geluidsoverlast installaties': 'Overlast Bedrijven en Horeca',
  'Overlast terrassen': 'Overlast Bedrijven en Horeca',
  'Stank horeca/bedrijven': 'Overlast Bedrijven en Horeca',
  'Stankoverlast': 'Overlast Bedrijven en Horeca',
  'Overlast door bezoekers (niet op terras)': 'Overlast Bedrijven en Horeca',
  'Overig horeca/bedrijven': 'Overlast Bedrijven en Horeca',
  'Overlast op het water - snel varen': 'Overlast op het water',
  'Overlast op het water - Vaargedrag': 'Overlast op het water',
  'Overlast op het water - geluid': 'Overlast op het water',
  'Overlast op het water - Gezonken boot': 'Overlast op het water',
  'Scheepvaart nautisch toezicht': 'Overlast op het water',
  'Overlast vanaf het water': 'Overlast op het water',
  'Overig boten': 'Overlast op het water',
  'Overig': 'Overig'
}

export default subToMainMap;
