export const FETCH_DEFAULT_TEXTS = 'src/DefaultTextsAdmin/FETCH_DEFAULT_TEXTS';
export const FETCH_DEFAULT_TEXTS_SUCCESS = 'src/DefaultTextsAdmin/FETCH_DEFAULT_TEXTS_SUCCESS';
export const FETCH_DEFAULT_TEXTS_ERROR = 'src/DefaultTextsAdmin/FETCH_DEFAULT_TEXTS_ERROR';
