name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: pre-Install
      run: npm i --unsafe-perm -g full-icu
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install
      run: npm ci
      env:
        NODE_ICU_DATA: /usr/local/lib/node_modules/full-icu
    - name: Lint
      run: npm run lint
    - name: Test
      run: npx jest --no-watchman --silent --coverage
      env:
        CI: true
    - name: Build
      run: npm run build --if-present
      env:
        GIT_COMMIT: $GITHUB_SHA
