name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: docker-compose -f action.docker-compose.yml -p sia-ci up --build --exit-code-from ci-container ci-container
        env:
          GIT_COMMIT: $GITHUB_SHA
