name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: apt-get install
        run: sudo apt-get install netcat git

      - name: ful--icu
        run: npm i --unsafe-perm -g full-icu

      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Copy environment.json
        run: echo {} > environment.conf.json

      - name: Build
        run: npm run build

      - name: Webhook
        uses: zzzze/webhook-trigger@master
        with:
          data: "{\"event_type\":\"build\"}"
          webhook_url: ${{ secrets.WEBHOOK_URL }}
