name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install, lint, test and build
      run: |
        npm ci
        npm run lint
        npm run test
        npm run build --if-present
      env:
        CI: true
